import 'package:process_run/shell.dart';

main() async {
  var shell = Shell(commentVerbose: true);
  await shell.run('''
    # Build web files
    flutter build web
  
    # Remove old directories in: ..\\meyn_lbh_simulation_web
    FOR /d %a IN ("..\\responsive_layout_grid_demo_web\\*.*") DO IF /i NOT "%~nxa"==".git" RD /S /Q "%a"
 
    # Remove old files in: ..\\responsive_layout_grid_demo_web
    DEL "..\\responsive_layout_grid_demo_web\\*.*" /Q

    # Copy build files to: ..\\responsive_layout_grid_demo_web
    XCOPY ".\\build\\web" "..\\responsive_layout_grid_demo_web" /S
  ''');

  shell = Shell(
    workingDirectory: '..\\responsive_layout_grid_demo_web',
    commentVerbose: true,
  );
  await shell.run('''
    # Add all files to git
    git add .
  
    # Commit to git
    git commit -m "Generated by responsive_layout_grid_demo/tool/publish.dart"
 
    # Push to git
    git push

    # Published on: https://domain-centric.github.io/responsive_layout_grid_demo_web
  ''');
}
