import 'dart:io';

import 'package:process_run/shell.dart';

main() async {
  var shell = Shell(commentVerbose: true);
  var sourceProjectName=Directory.current.path.split(Platform.pathSeparator).last;
  var gitRepositoryUserName='domain-centric';
  var gitRepositoryName='${sourceProjectName}_web';
  await shell.run('''
    # Build web files
    flutter build web
  
    # Remove old directories in: ..\\$gitRepositoryName
    FOR /d %a IN ("..\\$gitRepositoryName\\*.*") DO IF /i NOT "%~nxa"==".git" RD /S /Q "%a"
 
    # Remove old files in: ..\\$gitRepositoryName
    DEL "..\\$gitRepositoryName\\*.*" /Q

    # Copy build files to: ..\\$gitRepositoryName
    XCOPY ".\\build\\web" "..\\$gitRepositoryName" /S
  ''');

  shell = Shell(
    workingDirectory: '..\\$gitRepositoryName',
    commentVerbose: true,
  );
  await shell.run('''
    # Add all files to git
    git add .
  
    # Commit to git
    git commit -m "Generated by $sourceProjectName/tool/publish_as_web_app.dart"
 
    # Push to git
    git push

    # Published on: https://$gitRepositoryUserName.github.io/$gitRepositoryName/
  ''');
}